models:
  logistic_regression:
    max_iter: 1000
    C: 1.0
    solver: 'liblinear'
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
  
  svm:
    kernel: 'rbf'
    C: 1.0
    gamma: 'scale'
  
  naive_bayes:
    alpha: 1.0

vectorizer:
  type: 'tfidf'
  max_features: 1000
  ngram_range: [1, 2]
  min_df: 2
  max_df: 0.8
  stop_words: 'english'

preprocessing:
  lowercase: true
  remove_punctuation: true
  remove_stopwords: true